import { Open_Sans } from "next/font/google";
import "../styles/globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["italic", "normal"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en"
      className={`${openSans.variable} antialiased`}  
    >
      <body className="overflow-x-hidden max-w-screen">
        <div id="modal"></div>
        {children}
      </body>
    </html>
  );
}
